name: store screenshots

on:
  push:
    branches:
      - main
  pull_request:
  
permissions:
  contents: read
  checks: write
  id-token: write
  
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 19

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run all local screenshot tests (Roborazzi)
        id: screenshotsverify
        continue-on-error: true
        run: ./gradlew verifyRoborazziDebug

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: cancelled() != true
        with:
         report_paths: '**/build/test-results/*/TEST-*.xml'

      - name: Generate new screenshots if verification failed and it's a PR
        id: screenshotsrecord
        if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
        run: |
          ./gradlew recordRoborazziDebug

      - name: compare screenshot test
        id: compare-screenshot-test
        if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
        run: |
          ./gradlew compareRoborazziDebug --stacktrace

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.screenshotsrecord.outcome == 'success'
        with:
          file_pattern: '*/*.png'
          disable_globbing: true
          commit_message: "Updates screenshots"

      - name: Run unit tests
        if: always()
        run: ./gradlew testDebugUnitTest

      # Upload screenshots to GitHub Actions Artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: | 
            **/build/outputs/roborazzi
          retention-days: 30
